plugin:
    name: 'Image Resizer'
    description: 'Automatically resizes uploaded images to specified dimensions and compression with TinyPNG.'
    author: 'Petr Široký'
    icon: oc-icon-image
    homepage: 'https://octobercms.com/plugin/stheme-imageresize'
